@extends('layouts.dashboard')

@section('title', 'Reports Management')

@section('content')
<div class="container-fluid">
    <!-- Header -->
    <div class="d-flex justify-content-between align-items-center mb-6">
        <div>
            <h1 class="text-3xl font-display font-bold text-gray-900 mb-2">📊 Reports Management</h1>
            <p class="text-gray-600 font-body">Generate and manage career reports and analytics</p>
        </div>
        <button onclick="openGenerateReportModal()" class="btn-primary px-6 py-3 text-lg font-display font-bold shadow-lg hover:shadow-xl transition-all duration-300 transform hover:scale-105">
            <i class="fas fa-plus mr-2"></i>Generate Report
        </button>
    </div>

    <!-- Statistics Cards -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div class="card-enhanced p-6">
            <div class="flex items-center">
                <div class="p-3 rounded-full bg-gradient-to-r from-blue-500 to-blue-600 text-white mr-4">
                    <i class="fas fa-file-alt text-xl"></i>
                </div>
                <div>
                    <p class="text-sm font-medium text-gray-600">Total Reports</p>
                    <p class="text-2xl font-bold text-gray-900">{{ $reports->total() }}</p>
                </div>
            </div>
        </div>

        <div class="card-enhanced p-6">
            <div class="flex items-center">
                <div class="p-3 rounded-full bg-gradient-to-r from-green-500 to-green-600 text-white mr-4">
                    <i class="fas fa-chart-line text-xl"></i>
                </div>
                <div>
                    <p class="text-sm font-medium text-gray-600">Employment Reports</p>
                    <p class="text-2xl font-bold text-gray-900">{{ $reports->where('report_type', 'employment_summary')->count() }}</p>
                </div>
            </div>
        </div>

        <div class="card-enhanced p-6">
            <div class="flex items-center">
                <div class="p-3 rounded-full bg-gradient-to-r from-purple-500 to-purple-600 text-white mr-4">
                    <i class="fas fa-graduation-cap text-xl"></i>
                </div>
                <div>
                    <p class="text-sm font-medium text-gray-600">Program Analysis</p>
                    <p class="text-2xl font-bold text-gray-900">{{ $reports->where('report_type', 'program_analysis')->count() }}</p>
                </div>
            </div>
        </div>

        <div class="card-enhanced p-6">
            <div class="flex items-center">
                <div class="p-3 rounded-full bg-gradient-to-r from-orange-500 to-orange-600 text-white mr-4">
                    <i class="fas fa-trending-up text-xl"></i>
                </div>
                <div>
                    <p class="text-sm font-medium text-gray-600">Career Trends</p>
                    <p class="text-2xl font-bold text-gray-900">{{ $reports->where('report_type', 'career_trends')->count() }}</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Reports Table -->
    <div class="card-enhanced">
        <div class="p-6 border-b border-gray-200">
            <h3 class="text-lg font-display font-semibold text-gray-900">📋 Generated Reports</h3>
        </div>
        
        <div class="overflow-x-auto">
            <table class="min-w-full divide-y divide-gray-200">
                <thead class="bg-gray-50">
                    <tr>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Report</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Type</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Generated By</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                        <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                    </tr>
                </thead>
                <tbody class="bg-white divide-y divide-gray-200">
                    @forelse($reports as $report)
                        <tr class="hover:bg-gray-50 transition-colors duration-200">
                            <td class="px-6 py-4 whitespace-nowrap">
                                <div>
                                    <div class="text-sm font-medium text-gray-900">{{ $report->title }}</div>
                                    @if($report->description)
                                        <div class="text-sm text-gray-500">{{ Str::limit($report->description, 50) }}</div>
                                    @endif
                                </div>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap">
                                <span class="badge-enhanced px-3 py-1 text-xs font-medium">
                                    @switch($report->report_type)
                                        @case('employment_summary')
                                            📊 Employment Summary
                                            @break
                                        @case('program_analysis')
                                            🎓 Program Analysis
                                            @break
                                        @case('career_trends')
                                            📈 Career Trends
                                            @break
                                        @default
                                            {{ ucfirst(str_replace('_', ' ', $report->report_type)) }}
                                    @endswitch
                                </span>
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                                {{ $report->generatedBy->name ?? 'System' }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                {{ $report->generated_at ? $report->generated_at->format('M d, Y H:i') : $report->created_at->format('M d, Y H:i') }}
                            </td>
                            <td class="px-6 py-4 whitespace-nowrap text-sm font-medium">
                                <div class="flex space-x-2">
                                    <button onclick="viewReport({{ $report->id }})" class="text-blue-600 hover:text-blue-900 transition-colors duration-200">
                                        <i class="fas fa-eye"></i> View
                                    </button>
                                    <button onclick="downloadReport({{ $report->id }})" class="text-green-600 hover:text-green-900 transition-colors duration-200">
                                        <i class="fas fa-download"></i> Download
                                    </button>
                                    <button onclick="deleteReport({{ $report->id }})" class="text-red-600 hover:text-red-900 transition-colors duration-200">
                                        <i class="fas fa-trash"></i> Delete
                                    </button>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="5" class="px-6 py-12 text-center">
                                <div class="text-gray-500">
                                    <i class="fas fa-file-alt text-4xl mb-4"></i>
                                    <p class="text-lg font-medium">No reports generated yet</p>
                                    <p class="text-sm">Generate your first report to get started</p>
                                </div>
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if($reports->hasPages())
            <div class="px-6 py-4 border-t border-gray-200">
                {{ $reports->links() }}
            </div>
        @endif
    </div>
</div>

<!-- Generate Report Modal -->
<div id="generateReportModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden z-50">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
        <div class="mt-3">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg font-display font-bold text-gray-900">📊 Generate New Report</h3>
                <button onclick="closeGenerateReportModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            
            <form action="{{ route('admin.reports.generate') }}" method="POST">
                @csrf
                <div class="space-y-4">
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Report Type</label>
                        <select name="report_type" required class="input-enhanced w-full">
                            <option value="">Select report type...</option>
                            <option value="employment_summary">📊 Employment Summary</option>
                            <option value="program_analysis">🎓 Program Analysis</option>
                            <option value="career_trends">📈 Career Trends</option>
                        </select>
                    </div>
                    
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Report Title</label>
                        <input type="text" name="title" required class="input-enhanced w-full" placeholder="Enter report title...">
                    </div>
                    
                    <div>
                        <label class="block text-sm font-medium text-gray-700 mb-2">Description (Optional)</label>
                        <textarea name="description" rows="3" class="input-enhanced w-full" placeholder="Enter report description..."></textarea>
                    </div>
                </div>
                
                <div class="flex justify-end space-x-3 mt-6">
                    <button type="button" onclick="closeGenerateReportModal()" class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 transition-colors duration-200">
                        Cancel
                    </button>
                    <button type="submit" class="btn-primary px-4 py-2 text-sm font-medium">
                        <i class="fas fa-plus mr-2"></i>Generate Report
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Report Details Modal -->
<div id="reportDetailsModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden z-50">
    <div class="relative top-20 mx-auto p-5 border w-4/5 max-w-4xl shadow-lg rounded-md bg-white">
        <div class="mt-3">
            <div class="flex items-center justify-between mb-4">
                <h3 class="text-lg font-display font-bold text-gray-900">📊 Report Details</h3>
                <button onclick="closeReportDetailsModal()" class="text-gray-400 hover:text-gray-600">
                    <i class="fas fa-times"></i>
                </button>
            </div>
            
            <div id="reportContent" class="space-y-4">
                <!-- Report content will be loaded here -->
            </div>
            
            <div class="flex justify-end mt-6">
                <button onclick="closeReportDetailsModal()" class="btn-primary px-4 py-2 text-sm font-medium">
                    Close
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Delete Confirmation Modal -->
<div id="deleteReportModal" class="fixed inset-0 bg-gray-600 bg-opacity-50 overflow-y-auto h-full w-full hidden z-50">
    <div class="relative top-20 mx-auto p-5 border w-96 shadow-lg rounded-md bg-white">
        <div class="mt-3">
            <div class="flex items-center justify-center mb-4">
                <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 rounded-full bg-red-100">
                    <i class="fas fa-exclamation-triangle text-red-600"></i>
                </div>
            </div>
            
            <div class="text-center">
                <h3 class="text-lg font-medium text-gray-900 mb-2">Delete Report</h3>
                <p class="text-sm text-gray-500 mb-6">Are you sure you want to delete this report? This action cannot be undone.</p>
                
                <div class="flex justify-center space-x-3">
                    <button onclick="closeDeleteReportModal()" class="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-200 rounded-md hover:bg-gray-300 transition-colors duration-200">
                        Cancel
                    </button>
                    <button id="confirmDeleteReport" class="px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-md hover:bg-red-700 transition-colors duration-200">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
function openGenerateReportModal() {
    document.getElementById('generateReportModal').classList.remove('hidden');
}

function closeGenerateReportModal() {
    document.getElementById('generateReportModal').classList.add('hidden');
}

function viewReport(reportId) {
    // Load report details via AJAX
    fetch(`/admin/reports/${reportId}`)
        .then(response => response.json())
        .then(data => {
            document.getElementById('reportContent').innerHTML = `
                <div class="bg-gray-50 p-4 rounded-lg">
                    <h4 class="font-semibold text-gray-900 mb-2">${data.title}</h4>
                    <p class="text-sm text-gray-600 mb-4">${data.description || 'No description provided'}</p>
                    <div class="bg-white p-4 rounded border">
                        <pre class="text-sm text-gray-700 whitespace-pre-wrap">${JSON.stringify(data.data, null, 2)}</pre>
                    </div>
                </div>
            `;
            document.getElementById('reportDetailsModal').classList.remove('hidden');
        })
        .catch(error => {
            console.error('Error loading report:', error);
            alert('Error loading report details');
        });
}

function closeReportDetailsModal() {
    document.getElementById('reportDetailsModal').classList.add('hidden');
}

function downloadReport(reportId) {
    // Create download link
    const link = document.createElement('a');
    link.href = `/admin/reports/${reportId}/download`;
    link.download = `report_${reportId}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}

function deleteReport(reportId) {
    document.getElementById('confirmDeleteReport').onclick = function() {
        fetch(`/admin/reports/${reportId}`, {
            method: 'DELETE',
            headers: {
                'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').getAttribute('content'),
                'Content-Type': 'application/json',
            },
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                location.reload();
            } else {
                alert('Error deleting report');
            }
        })
        .catch(error => {
            console.error('Error deleting report:', error);
            alert('Error deleting report');
        });
        
        closeDeleteReportModal();
    };
    
    document.getElementById('deleteReportModal').classList.remove('hidden');
}

function closeDeleteReportModal() {
    document.getElementById('deleteReportModal').classList.add('hidden');
}

// Close modals when clicking outside
document.addEventListener('click', function(event) {
    const generateModal = document.getElementById('generateReportModal');
    const detailsModal = document.getElementById('reportDetailsModal');
    const deleteModal = document.getElementById('deleteReportModal');
    
    if (event.target === generateModal) {
        closeGenerateReportModal();
    }
    if (event.target === detailsModal) {
        closeReportDetailsModal();
    }
    if (event.target === deleteModal) {
        closeDeleteReportModal();
    }
});
</script>
@endsection
